name: hlibrary
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hexcolor: ^3.0.1
  flutter_riverpod: 2.4.9
  provider: ^6.1.1
  flutter_hooks: any
  hooks_riverpod: any
  animated_bottom_navigation_bar: ^1.3.0
  curved_navigation_bar: ^1.0.3
  salomon_bottom_bar: ^3.3.2
  animate_do: ^3.1.2
  shadow: ^1.5.0
  flutter_helper_utils: ^2.0.1
  iconsax: ^0.0.8
  flutter_color_utils: ^0.0.1
  flutter_screenutil: ^5.9.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.2
  line_awesome_flutter: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  email_validator: '^2.1.16'
  password_field_validator: ^0.0.1
  carousel_slider: ^4.0.0
  fluttertoast: ^8.2.4
  get: ^4.6.6
  flutter_rating_bar: ^4.0.1
  cloud_firestore: ^4.13.5
  image_picker: ^1.0.5
  firebase_storage: ^11.5.6
  firebase_app_check: ^0.2.1+8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter_launcher_icons:
  android: true
  image_path: "assets/images/logo.png"
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
