// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChu00oYXfZms93p2N-S0pQ9yEFnJW3knM',
    appId: '1:416101594277:web:2a8b63d9d51a6d0165494c',
    messagingSenderId: '416101594277',
    projectId: 'hlibrary-e7f50',
    authDomain: 'hlibrary-e7f50.firebaseapp.com',
    storageBucket: 'hlibrary-e7f50.appspot.com',
    measurementId: 'G-BJ1HKJBGYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAqVkeUnhgGTAQ82u5sjSXflRk6iJlWyk',
    appId: '1:416101594277:android:04a255e604db374c65494c',
    messagingSenderId: '416101594277',
    projectId: 'hlibrary-e7f50',
    storageBucket: 'hlibrary-e7f50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2HXS2veif8K7iwEXhPkyzUJ5P282ZHeI',
    appId: '1:416101594277:ios:07f22839c784ca8565494c',
    messagingSenderId: '416101594277',
    projectId: 'hlibrary-e7f50',
    storageBucket: 'hlibrary-e7f50.appspot.com',
    iosBundleId: 'com.example.hlibrary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2HXS2veif8K7iwEXhPkyzUJ5P282ZHeI',
    appId: '1:416101594277:ios:300d9decd8c1f1b265494c',
    messagingSenderId: '416101594277',
    projectId: 'hlibrary-e7f50',
    storageBucket: 'hlibrary-e7f50.appspot.com',
    iosBundleId: 'com.example.hlibrary.RunnerTests',
  );
}
