// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9GapP31tOrTzc59KpgCKcu9aCCQi6vhA',
    appId: '1:799173492059:web:848ea9a1186aee3f12ae7e',
    messagingSenderId: '799173492059',
    projectId: 'hlibrary7',
    authDomain: 'hlibrary7.firebaseapp.com',
    storageBucket: 'hlibrary7.appspot.com',
    measurementId: 'G-QT5F5BWHG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjE-ej5ZiyKcsP8tZ1ymOCvZJgAJxHUzA',
    appId: '1:799173492059:android:c058fe44be4aa15612ae7e',
    messagingSenderId: '799173492059',
    projectId: 'hlibrary7',
    storageBucket: 'hlibrary7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK0Av3qed10uIzbZnKFD70OfCDLCgSd-o',
    appId: '1:799173492059:ios:202a7f4bfa638b1712ae7e',
    messagingSenderId: '799173492059',
    projectId: 'hlibrary7',
    storageBucket: 'hlibrary7.appspot.com',
    iosBundleId: 'com.example.hlibrary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK0Av3qed10uIzbZnKFD70OfCDLCgSd-o',
    appId: '1:799173492059:ios:b96326388e6087f112ae7e',
    messagingSenderId: '799173492059',
    projectId: 'hlibrary7',
    storageBucket: 'hlibrary7.appspot.com',
    iosBundleId: 'com.example.hlibrary.RunnerTests',
  );
}
